family/urls.py
from django.contrib import admin


from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from family_site.views import AnniversaryViewSet, GwBankViewSet, WrBankViewSet

from family.views import SansuTemplateView #UserCreateView, UserCreateDoneTemplateView

router = routers.DefaultRouter()
router.register(r'anniversary_api', AnniversaryViewSet)
router.register(r'gwbank_api', GwBankViewSet)
router.register(r'wrbank_api', WrBankViewSet)


urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),


    # serializer
    path('api/', include(router.urls)),  # api 홈 디렉토리
    path('api-auth/', include('rest_framework.urls')),
    
 
    path('', SansuTemplateView.as_view(), name='sansu'),
    path('', include('family_site.urls')),

    # 회원, 로그인
    path('accounts/', include('django.contrib.auth.urls')),
    #url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    #url(r'^accounts/register/done/$', UserCreateDoneTemplateView.as_view(), name='register_done'),

    path('summernote/', include('django_summernote.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

family_site/urls.py
from django.urls import path, include


from . import views

app_name = 'family_site'
urlpatterns = [

    # daily urls
    path('daily_create/', views.DailyCreateView.as_view(), name='daily_create'),
    path('daily_list/', views.DailyListView.as_view(), name='daily_list'),
    path('daily_detail/<int:daily_id>/', views.DailyDetailView.as_view(), name='daily_detail'),

    # anniversary urls
    path('anniversary_create/', views.AnniversaryCreateView.as_view(), name='anniversary_create'),
    path('anniversary_list/', views.AnniversaryListView.as_view(), name='anniversary_list'),

    # 광주은행
    path('gwbank_create/', views.GwBankCreateView.as_view(), name='gwbank_create'),
    path('gwbank_list/', views.GwBankListView.as_view(), name='gwbank_list'),

    # 우리은행
    path('wrbank_create/', views.WrBankCreateView.as_view(), name='wrbank_create'),
    path('wrbank_list/', views.WrBankListView.as_view(), name='wrbank_list'),
    
    # 게시판
    path('note_create/', views.NoteCreateView.as_view(), name='note_create'),
    path('note_list/', views.NoteListView.as_view(), name='note_list'),
    path('note_detail/<int:note_id>/', views.NoteDetailView.as_view(), name='note_detail'),
    path('note_update/<int:note_id>/', views.NoteUpdateView.as_view(), name='note_update'),
    path('note_delete/<int:note_id>/', views.NoteDeleteView.as_view(), name='note_delete'),

    # # 게시판 댓글
    path('notecomment_create/<int:pk>/', views.NoteCommentCreateView.as_view(), name='notecomment_create'),
    path('notecomment_update/<int:note_pk>)/<int:pk>/', views.NoteCommentUpdateView.as_view(), name='notecomment_update'),
    path('notecomment_delete/<int:note_pk>)/<int:pk>/', views.NoteCommentDeleteView.as_view(), name='notecomment_delete'),
    #
    #
    # 카카오 로그인
    path('kakao_login/', views.kakaoLoginTemplateView.as_view(), name='kakao_login'),

]

family_site/forms.py
import datetime
#from django.forms.extras.widgets import SelectDateWidget
from django.forms.widgets import Select, MultiWidget, DateInput, TextInput, Widget

from django import forms
#from django.forms import extras   extras 대신 forms 를 사용

from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from . models import Daily, Anniversary, GwBank, WrBank, Note, NoteComment
#BIRTH_YEAR_CHOICES = ('2012', '2013', '2014', '2015','2016','2017','2018','2019','2020')
THIS_YEAR = datetime.date.today().year
# 날마다 폼
class DailyForm(forms.ModelForm):
    #daily_date = forms.DateField(widget=extras.SelectDateWidget(),label='날자',help_text="  ")
    daily_date = forms.DateField(widget=forms.SelectDateWidget(), label='날자', help_text="  ")
    class Meta:
        model = Daily
        fields = ('daily_date', 'daily_day', 'daily_content', )
        widgets = {
            'daily_content' : SummernoteWidget(),
        }

# 자동 완성 끄기
#  'autocomplete'='off' 를 attrs에 추가하면됩니다.    

# 기념일 폼
class AnniversaryForm(forms.ModelForm):
    #anniversary_name = forms.CharField(widget=forms.TextInput(attrs=dict(required=True, max_length=10)),label=('연락처'))
    #anniversary_date = forms.DateField(widget=SelectDateWidget,initial=datetime.date.today,label=_("날짜"))
    anniversary_date = forms.DateField(widget=forms.SelectDateWidget(),label='날자',help_text="  ")
   
    class Meta:
        model = Anniversary
        fields = ('anniversary_date', 'anniversary_day', 'anniversary_name', 'anniversary_lunar_date', )
        


# 광주은행 폼
class GwBankForm(forms.ModelForm):
    #gwbank_date = forms.DateField(required=False, widget=extras.SelectDateWidget(years=BIRTH_YEAR_CHOICES),label='날자',help_text="  ")
    gwbank_date = forms.DateField(initial=datetime.date.today(), widget=forms.SelectDateWidget(None, range(2014, THIS_YEAR+10)))
    class Meta:
        model = GwBank
        fields = ('gwbank_name_choices', 'gwbank_date', 'gwbank_income', 'gwbank_money', 'gwbank_name', 'gwbank_execution', 'gwbank_note', )


# 우리은행
class WrBankForm(forms.ModelForm):
    #wrbank_date = forms.DateField(widget=extras.SelectDateWidget(),label='날자',help_text="  ")
    wrbank_date = forms.DateField(initial=datetime.date.today(), widget=forms.SelectDateWidget(None, range(2014, THIS_YEAR+10)))
    class Meta:
        model = WrBank
        fields = ('wrbank_date', 'wrbank_deposit_withdrawal', 'wrbank_money1', 'wrbank_note', 'wrbank_money2',  'wrbank_money3', 'wrbank_aggregate', 'wrbank_loan_balance', 'wrbank_bankbook_balance', )


# 게시판
class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('note_title', 'note_content', )
        widgets = {
            'note_content': SummernoteWidget(),
        }


# 게시판 댓글
class NoteCommentForm(forms.ModelForm):
    class Meta:
        model = NoteComment
        fields = ('notecomment_content', )

# 게시판 수정
class NoteCommentUpdateForm(forms.ModelForm):
    class Meta:
        model = NoteComment
        fields = ('notecomment_content', )

family_site/views.py
from django.shortcuts import render, get_object_or_404, resolve_url, reverse, redirect
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

# 로그인 페이지로 가기
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
import pandas

from datetime import date, datetime, timedelta
from django.http import HttpResponse, JsonResponse

from django.db.models import Q, F, Sum, Count, Case, When



#from django.contrib.auth.models import User
from rest_framework import viewsets

import pickle, datetime


from . serializers import AnniversarySerializer, GwBankSerializer, WrBankSerializer

from . models import Daily, Anniversary, GwBank, WrBank, Note, NoteComment
from . forms import DailyForm, AnniversaryForm, GwBankForm, WrBankForm, NoteForm, NoteCommentForm, NoteCommentUpdateForm

# Create your views here.


# 로그인 리다이렉트
class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

# 날마다
class DailyCreateView(LoginRequiredMixin, CreateView):
    model = Daily 
    form_class = DailyForm
    template_name = 'family_site/daily/daily_create.html'
    success_url = reverse_lazy('family_site:daily_list')

    def get_queryset(self):
        return Daily.objects.all()

class DailyListView(ListView):
    model = Daily
    template_name = 'family_site/daily/daily_list.html'

class DailyDetailView(DetailView):
    model = Daily
    template_name = 'family_site/daily/daily_detail.html'    

# 기념일
class AnniversaryViewSet(viewsets.ModelViewSet):
    queryset = Anniversary.objects.all()
    serializer_class = AnniversarySerializer

class AnniversaryCreateView(LoginRequiredMixin, CreateView):
    model = Anniversary
    form_class = AnniversaryForm
    template_name = 'family_site/anniversary/anniversary_create.html'
    success_url = reverse_lazy('family_site:anniversary_list')

class AnniversaryListView(ListView):
    model = Anniversary
    template_name = 'family_site/anniversary/anniversary_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        anni = date(2018,3,31)
       
        #anniver = anni.strftime('%Y-%m-%d') 이렇게 문자열화 하면 에러난다
        context['a'] = anni
        b = date.today()
        
        # context['c'] = repr(b)
        # f = datetime('2018-04-17', '%Y-%m-%d')
        # context['ff'] = str(f)[:-1]

       
        return context

# 광주은행
class GwBankViewSet(viewsets.ModelViewSet):
    queryset = GwBank.objects.all()
    serializer_class = GwBankSerializer

class GwBankCreateView(LoginRequiredMixin, CreateView):
    model = GwBank
    template_name = 'family_site/gwbank/gwbank_create.html'    
    form_class = GwBankForm
    #fields = ('id', 'gwbank_name_choices', 'gwbank_date', 'gwbank_income', 'gwbank_money', 'gwbank_name', 'gwbank_execution', 'gwbank_note',)
    #success_url = reverse_lazy('family_site:gwbank_list')
    # CreateView는 fields 를 적어주지 않으면 에러나고, form.html 에서 필드가 표시되지 않는다

    def form_valid(self, form):
        form = form.save(commit=False)
        form.gwbank_execution = self.default=0
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('family_site:gwbank_list')


class GwBankListView(ListView):
    model = GwBank
    template_name = 'family_site/gwbank/gwbank_list.html'
    paginate_by = 30

    def get_queryset(self):
        return GwBank.objects.all()

    def get_context_data(self, **kwarges):
        context = super(GwBankListView, self).get_context_data(**kwarges)
        context['chaesun'] = GwBank.objects.filter(gwbank_name='이채순').aggregate(이채순=Sum(F('gwbank_money')))['이채순'] or 0
        context['gichang'] = GwBank.objects.filter(gwbank_name='이기창').aggregate(이기창=Sum(F('gwbank_money')))['이기창'] or 0
        context['hwasun'] = GwBank.objects.filter(gwbank_name='이화순').aggregate(이화순=Sum(F('gwbank_money')))['이화순'] or 0
        #context['k'] = GwBank.objects.filter(gwbank_name='이채순')
        context['k'] = GwBank.objects.all()

        context['total'] = context['chaesun'] + context['gichang'] + context['hwasun']

        return context


# 우리은행
class WrBankViewSet(viewsets.ModelViewSet):
    queryset = WrBank.objects.all()
    serializer_class = WrBankSerializer

class WrBankCreateView(LoginRequiredMixin, CreateView):
    model = WrBank
    template_name = 'family_site/wrbank/wrbank_create.html'
    #success_url = reverse_lazy('family_site:wrbank_list')
    form_class = WrBankForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.wrbank_money1 = self.default=0
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('family_site:wrbank_list')

    

class WrBankListView(ListView):
    model = WrBank
    template_name = 'family_site/wrbank/wrbank_list.html'
    paginate_by = 30

    def get_queryset(self):        
        return WrBank.objects.all()

    def get_context_data(self, **kwarges):
        context = super(WrBankListView, self).get_context_data(**kwarges)

        # 우리은행 엑셀 불러오기
        bank = pandas.read_excel('woori_bank.xlsx')

        # 대출 이자
        woori_a = bank['대출이자'].count()
        woori_b = bank['대출이자'].sum().astype(int)
        context['woori_a'] = woori_a
        context['woori_b'] = woori_b

        # 대출 원금
        woori_e = bank['대출원금'].count().astype(int)
        woori_f = bank['대출원금'].sum().astype(int)
        context['woori_e'] = woori_e
        context['woori_f'] = woori_f

        # 대출 이자 + 대출 원금
        woori_c = bank['합    계'].count()
        woori_d = bank['합    계'].sum().astype(int)
        context['woori_c'] = woori_c
        context['woori_d'] = woori_d

        # 이상순 이름을 찾기위해 loc함수 시용, 회수와 합게 함수 사용
        # .loc 메소드는 라벨과 정수로, iloc 는 정수로만 접근 가능하며, iloc 는 음수를 지원해서 마지막 행,열,셀을 참조할 수 있다
        cu = bank[['설    명', '금    액']]
        cu_c = cu.loc[cu['설    명'].str.contains('이상순'), ['금    액']].count()
        cu_d = cu.loc[cu['설    명'].str.contains('이상순'), ['금    액']].sum()

        # 사천만원 더하기
        cu_d = cu_d + 40000000
        context['cu_c'] = cu_c
        context['cu_d'] = cu_d

        """\ 대출잔액
        이 문법이 맞는지는 모름
        DataFrame에서 3자리수 콤마와 문자열을 제거하지 못해 이런 쌩쇼를 함. \        
        """
        count = bank.iloc[[-1], [-2]]  # iloc 메소드로 마지막 행, 열의 마지막 2번째 데이터를 가져온다
        countt = count.values[-1]  # 변수를 한번 더 적용하면 count DataFrame 형을 리스트 값으로 변형시켜 values 메소드로 값을 취한다
        for ii in countt:  # for문으로 리스트을 벗긴다
            print(ii)
        context['ii'] = ii

        # 통장 잔액도 대출 잔액과 같다
        count1 = bank.iloc[[-1], [-1]]
        count11 = count1.values[-1]
        for i in count11:
            print(i)
        context['i'] = i

        f = bank.to_html()

        context['aa'] = f # 새로운 우리은행 판다 엑셀 작업 끝






        context['interest'] = WrBank.objects.all().aggregate(대출이자총액=Sum(F('wrbank_money2')))['대출이자총액'] or 0
        context['principal'] = WrBank.objects.all().aggregate(원금총액=Sum(F('wrbank_money3')))['원금총액'] or 0
        context['deposit_withdrawal'] = WrBank.objects.all().aggregate(대출이자원금총액=Sum(F('wrbank_money2')+F('wrbank_money3')))['대출이자원금총액'] or 0

        context['kk'] = WrBank.objects.filter(wrbank_money2__gt=0).count
        context['kkk'] = WrBank.objects.filter(wrbank_money3__gt=0).count

        context['lee_sang_soon'] = WrBank.objects.filter(wrbank_note__startswith='이상순(가족)').aggregate(금액=Sum(F('wrbank_money1')))['금액'] or 0

        context['lee_sang_soon_count'] = WrBank.objects.filter(wrbank_note__startswith='이상순(가족)').count

        
        return context


# 게시판
class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    template_name = 'family_site/note/note_create.html'
    form_class = NoteForm

    def form_valid(self, form):
        form = form.save(commit=False)
        form.note_author = self.request.user
        form.save()
        return super(NoteCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('family_site:note_list')


class NoteListView(ListView):
    model = Note
    template_name = 'family_site/note/note_list.html'
    paginate_by = 4

    def get_queryset(self, *args, **kwargs):
        return Note.objects.select_related('note_author').all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class NoteDetailView(LoginRequiredMixin, DetailView):
    model = Note
    template_name = 'family_site/note/note_detail.html'

class NoteUpdateView(UpdateView):
    model = Note
    form_class = NoteForm
    template_name = 'family_site/note/note_create.html'
    success_url = reverse_lazy('family_site:note_list')


class NoteDeleteView(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy('family_site:note_list')
    template_name = 'family_site/note/note_confirm_delete.html'



# 게시판 댓글
class NoteCommentCreateView(LoginRequiredMixin, CreateView):
    model = NoteComment
    template_name = 'family_site/notecomment/notecomment_create.html'
    form_class = NoteCommentForm

    def form_valid(self, form):
        kkk = form.save(commit=False)
        kkk.note = get_object_or_404(Note, pk=self.kwargs['pk'])
        kkk.notecomment_author= self.request.user
        kkk.save()
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url(self.object.note)


class NoteCommentUpdateView(LoginRequiredMixin, UpdateView):
    model = NoteComment
    template_name = 'family_site/notecomment/notecomment_create.html'
    form_class = NoteCommentForm

    def get_success_url(self):
        return resolve_url(self.object.note)

class NoteCommentDeleteView(LoginRequiredMixin, DeleteView):
    model = NoteComment

family_site/templates/family_site/note/note_confirm_delete.html
{% extends 'main_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %} {% static 'family_site/css/note/note_list.css' %} {% endblock stylesheet %}

{% block content1 %}
<br>
<h3 style='color:brown'>삭제 할까요?</h3>
<br><br>

<form method="post" action="">{% csrf_token %}
    {{ form|crispy }}
    <input class='btn btn-danger' type='submit' value='삭제'>
    <a class='btn btn-primary' href="{% url 'family_site:note_list' %}">취 소</a><br>
</form><br>
       
    
{% endblock content1 %}

family_site/templates/family_site/note/note_create.html
{% extends 'main_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %} {% static 'family_site/css/note/note_create.css' %} {% endblock stylesheet %}

{% block content1 %}            
            <p>사진 사이즈가 크면 등록되지 않습니다.</p>
            <form action='' method='post' enctype="multipart/form-data">{% csrf_token %}  
                {{ form|crispy }}  
                <input class="btn btn-success" type="submit" value="글완료" />    
                <a class='btn btn-primary' href="{% url 'family_site:note_list' %}">취 소</a><br><br><br>
            </form><br><br><br>
               
{% endblock content1 %}

family_site/templates/family_site/note/note_detail.html
{% extends 'main_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %} {% static 'family_site/css/note/note_detail.css' %} {% endblock stylesheet %}

{% block content1 %}

    <div id='note_detail'>
   
        <h4 id='title' class="alert alert-info" role="alert"> {{ object.note_title }}</h4>
        <p>글쓴이 : {{ object.note_author }} <span> 등록일 : {{ object.note_created_date|date:'Y-m-d t:m:s' }}</span></p>
        <hr>
        <p>{{ object.note_content|safe|linebreaksbr }}</p>                       
    </div><br><br>
    
    
    {% if user.is_active %}
        <a class="btn btn-default" href="{% url 'family_site:notecomment_create' pk=note.pk %}">댓글 쓰기</a>
    {% endif%}
    {% if note.note_author == request.user %}
        <a class='btn btn-default' href="{% url 'family_site:note_update' pk=note.id %}">수정</a>
        <a class='btn btn-default' href="{% url 'family_site:note_delete' pk=note.id %}">삭제</a>
        <a class='btn btn-default' href="{% url 'family_site:note_list' %}">목록</a>
    {% endif %}  
<br><br><hr>

{% for i in note.comments.all %}
<div id='comments_count'>
        {{i.note.comments.count}}의 댓글이 있습니다.
</div>
<div id='comment'>
    <ul>
        <li>{{i.notecomment_author}}
            <span>{{ i.notecomment_publish_date|date:'Y-m-d H:m:s' }}</span>
        
            {% if i.notecomment_author == request.user %}
                <span><a href='{% url 'family_site:notecomment_update' note.pk i.pk %}'>수정</a></span>
                <span><a href='{% url 'family_site:notecomment_delete' note.pk i.pk %}'>삭제</a></span>
            {% endif %}
        </li> 
            <li>{{ i.notecomment_content|linebreaksbr }}</li>          
               
    </ul>
</div>
{% endfor %}

    <p>
        

        {% if object.get_next_by_note_created_date %}
            <a class='btn btn-info' href="{{ object.get_next_note_created_date.get_absolute_url }}">이전글</a>
        {% endif %}  
        
        {% if object.get_previous_by_note_created_date %}
            <a class="btn btn-info" href="{{ object.get_previous_note_created_date.get_absolute_url }}">다음글</a>
        {% endif %}

        

          
    </p><br><br><br><br><br><br><br>

{% endblock content1 %}

family_site/templates/family_site/note/note_list.html
{% extends 'main_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %} {% static 'family_site/css/note/note_list.css' %} {% endblock stylesheet %}

{% block content1 %}

    <table class='table table-bordered table-hover'>
        <thead>
            <tr>
                <th>번 호</th>
                <th>이 름</th>
                <th>제 목</th>
                <th>날 자</th>            
            </tr>
        </thead>
        <tbody>
            <tr>{% for i in object_list %}
                <td>{{ i.id }}</td>
                <td>{{ i.note_author }}</td>
                <td>                
                    <a href="{{ i.get_absolute_url }}">{{ i.note_title|truncatechars:50 }}
                        {% if i.comments.count == 0 %}
                          {{''}}
                        {%else%}
                          <span>{{i.comments.count}}</span></a>
                        {% endif %}
                </td>
                <td>{{ i.note_created_date|date:'Y-m-d H:m:s' }}</td>
            </tr>{% endfor %}
        </tbody>
    </table>

    {% if user.is_active %}
    <a class='btn btn-default' href="{% url 'family_site:note_create' %}">글쓰기</a>
    
    {% endif %}

    <div id="note_pagination">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
    </div><!-- pagination end -->     
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content1 %}

family_site/templates/family_site/note/note_update.html
{% extends 'main_layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block stylesheet %} {% static 'family_site/css/note/note_list.css' %} {% endblock stylesheet %}

{% block content1 %}

<form method="post" action="">{% csrf_token %}
    {{ form|crispy }}
</form>
   

<a class='btn btn-primary' href="{% url 'family_site:note_create' %}">글수정</a>
<a class='btn btn-primary' href="{% url 'website:note_list' %}">취 소</a><br>
       
    
{% endblock content1 %}