family/urls.py
from django.contrib import admin


from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from family_site.views import AnniversaryViewSet, GwBankViewSet, WrBankViewSet

from family.views import SansuTemplateView #UserCreateView, UserCreateDoneTemplateView

router = routers.DefaultRouter()
router.register(r'anniversary_api', AnniversaryViewSet)
router.register(r'gwbank_api', GwBankViewSet)
router.register(r'wrbank_api', WrBankViewSet)


urlpatterns = [

    path('admin/', admin.site.urls),

    path('accounts/', include('allauth.urls')),


    # serializer
    path('api/', include(router.urls)),  # api 홈 디렉토리
    path('api-auth/', include('rest_framework.urls')),
    
 
    path('', SansuTemplateView.as_view(), name='sansu'),
    path('', include('family_site.urls')),

    # 회원, 로그인
    path('accounts/', include('django.contrib.auth.urls')),
    #url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    #url(r'^accounts/register/done/$', UserCreateDoneTemplateView.as_view(), name='register_done'),

    path('summernote/', include('django_summernote.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

family_site/urls.py
from django.urls import path, include


from . import views

app_name = 'family_site'
urlpatterns = [

    # daily urls
    path('daily_create/', views.DailyCreateView.as_view(), name='daily_create'),
    path('daily_list/', views.DailyListView.as_view(), name='daily_list'),
    path('daily_detail/<int:daily_id>/', views.DailyDetailView.as_view(), name='daily_detail'),

    # anniversary urls
    path('anniversary_create/', views.AnniversaryCreateView.as_view(), name='anniversary_create'),
    path('anniversary_list/', views.AnniversaryListView.as_view(), name='anniversary_list'),

    # 광주은행
    path('gwbank_create/', views.GwBankCreateView.as_view(), name='gwbank_create'),
    path('gwbank_list/', views.GwBankListView.as_view(), name='gwbank_list'),

    # 우리은행
    path('wrbank_create/', views.WrBankCreateView.as_view(), name='wrbank_create'),
    path('wrbank_list/', views.WrBankListView.as_view(), name='wrbank_list'),
    
    # 게시판
    path('note_create/', views.NoteCreateView.as_view(), name='note_create'),
    path('note_list/', views.NoteListView.as_view(), name='note_list'),
    path('note_detail/<int:note_id>/', views.NoteDetailView.as_view(), name='note_detail'),
    path('note_update/<int:note_id>/', views.NoteUpdateView.as_view(), name='note_update'),
    path('note_delete/<int:note_id>/', views.NoteDeleteView.as_view(), name='note_delete'),

    # # 게시판 댓글
    path('notecomment_create/<int:pk>/', views.NoteCommentCreateView.as_view(), name='notecomment_create'),
    path('notecomment_update/<int:note_pk>)/<int:pk>/', views.NoteCommentUpdateView.as_view(), name='notecomment_update'),
    path('notecomment_delete/<int:note_pk>)/<int:pk>/', views.NoteCommentDeleteView.as_view(), name='notecomment_delete'),
    #
    #
    # 카카오 로그인
    path('kakao_login/', views.kakaoLoginTemplateView.as_view(), name='kakao_login'),

]

templates/main_layout.html
<!DOCTYPE html>
{% load static %}
{% load humanize %}

<html lang="ko">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1,  maximum-scale=1.0"/>

    <title> {% block title %} Sansu-Memory {% endblock title %} </title>     
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Miltonian+Tattoo|Permanent+Marker|Risque" />
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/main_layout.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}  {% endblock stylesheet %}" />

    <link rel="shortcut icon" href="#">


    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>    

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

<body>
<div data-role="page">
<div id="base_page_wrap"><!-- 전체페이지 wrapper 시작 div -->

    <div class="container-fluid" id="nav">
            <ul class="nav nav-tabs">
            <li class="active"><a href="{% url 'sansu' %}">Home</a></li>  
            <li><a href="{% url 'family_site:daily_list' %}">일 상</a></li>    
            <li><a href="{% url 'family_site:anniversary_list' %}">기념일</a></li> 
            <li><a href="{% url 'family_site:wrbank_list' %}">은 행</a></li>


            <li><a href="{% url 'family_site:note_list' %}">게시판</a></li>
            <li id='login_signup'>
                {% if user.is_active %}
                    <span class='welcome'>Welcome<strong>{% firstof user_get_short_name user.get_username  %}</strong>&nbsp;&nbsp;<a class='btn btn-default' href="{% url 'account_logout' %}">로그아웃</a></span>
                {% else %}                
                    <span class='welcome'>
                        <a class='btn btn-default' href='{% url 'family_site:kakao_login' %}'>로그인</a>


                    </span>
                {% endif %}
            </li>
           </ul>
    </div><!-- nav-container-fluid end-->    

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <h4 class="alert alert-success" role="alert">Sansu-Memory &nbsp;&nbsp;{% now 'Y.m.d' %}</h4>
                
                          
                {% block content1 %}

                {% for name in birthday %}
                    <div id='birthday'  class="alert alert-warning" role="alert" style='diplay:none; color:black;'><strong> {{ name }} </strong></div>
                {% endfor %}

                <div id='birthday1'  class="alert alert-warning" role="alert" style='display:none; color:black;'></div>

                <div id='birthday2'  class="alert alert-warning" role="alert" style='display:none; color:black;'></div>

                <div id='hospitalized'>
                    <ul>입원일자</ul>
                    <ul>
                        <li>어머님 전대병원 입원기간 : 2017.06.26(월) ~ 2017.08.28(월), <span>{{ cnuh_3.days }}</span>일({{ cnuh_1|timesince }} &nbsp;전).  </li>
                        <li>에스웰 요양병원 : 2017.08.28(월) ~ 2017.08.29(화), <span>1</span>일.</li>
                        <li>광주시립제2요양병원 : 2017.08.29일(화) ~ 2020.02.25(화). <span>{{ convalescentHospital_3.days }}</span>일 입원. ({{ convalescentHospital_1|timesince }} &nbsp;전).</li>
                        <li>광주시립제2요양병원이 코로나 바이러스 감염병전담병원으로 지정되어 화순군립요양병원으로 옮기심.</li>
                        <li>화순군립요양병원 : 2020.02.25일(화) 360호실에 입원, 27일 366호실로 옮기심. <span> {{ hoasun_nursing_home_sum.days }}일 입원</span></li>
                        <li>화순군립요양병원에서 2020.05.26일 광주시립제2요양병원으로 옮기심. <span> {{ gw2_nursing_home_sum.days }}일 경과</span></li>
                        <li>지금까지 <span>{{ hospitalization }}</span>일({{ hospitalization_timesince|timesince }} 전)</li>
                    </ul>
                </div><br>


                <div id='now_appointment'>
                    <ul>진료예약</ul>
                    <ul>
                        <li>안 과 : 2020.06.26일(금요일, 11시 20분) 전대병원 안과 예약(3동 2층, 성미선 교수) : {{ ophthalmology_1 }}</li>
                    </ul> 
                </div> 


                <div id='appointment'>
                    <ul>지난 진료 내역</ul>
                    <ul>
                        <li>안 과 : 2020.01.10일(금요일, 10시 10분) 전대병원 안과 예약(3동 2층, 성미선 교수) : {{ ophthalmology_0 }}</li>

                        <li>신경외과 : 2018.04.26일(목요일, 11:20시) 전대병원 신경외과 예약(1동 1층, 이정길 교수) :
                        
                            {% if neurosurgery_1 > neurosurgery_2 %}
                                <span> {{neurosurgery_3.days }}</span>일 남았습니다.
                            {% elif neurosurgery_1 == neurosurgery_2 %}
                                 <span>오늘은 진료일입니다!</span>
                            {% else %}
                                <span> {{ neurosurgery_4.days }}</span>일 지났습니다.
                            {% endif %} 
                        </li>   
                    </ul> 
                </div><br><br>

                <div id='qrcode'>
                    <ul>SANSU QR(Quick Response) CODE</ul>
                    <ul>
                       <li> &nbsp;&nbsp;&nbsp;<img src="{% static 'images/sansu.png' %}" title="sansu qrcode('Quick Response')" alt='qr code' width='200px'  /></li>
                    </ul>
                </div>
             {% endblock content1 %}

            </div><!-- col-xs-12 end -->
        </div><!-- row end -->
    </div><!-- class  container end-->

    <!-- 2번째 container_fluid -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">


    {% block content2 %}


{% endblock content2 %}
     
            
            </div><!-- col-xs-12 end -->
        </div><!-- row end -->
    </div><!-- class  container end-->


    {% block footer %}
    {% endblock footer %}

    {% block script %}
    {% endblock script %}
</div><!-- 전체페이지 base_page_wrap end -->
</div> <!-- data-role="page: -->
    <br><br><br><br><br><br>
<script src="{% static 'js/anniversary.js' %}"></script>
<script src="{% static 'family_site/js/gwbank/gwbank.js' %}"></script>
<script src="{% static 'family_site/js/wrbank/wrbank.js' %}"></script>


</body>
</html>